// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlcgen

import (
	"time"
)

type Env struct {
	ID         int64
	Name       string
	Comment    *string
	CreateTime time.Time
	UpdateTime time.Time
}

type EnvVarLocal struct {
	ID         int64
	EnvID      int64
	Name       string
	Comment    *string
	CreateTime time.Time
	UpdateTime time.Time
	Value      string
}

type EnvVarUniqueName struct {
	ID    int64
	EnvID int64
	Name  string
}

type KeyringEntry struct {
	ID         int64
	Name       string
	Comment    *string
	CreateTime time.Time
	UpdateTime time.Time
}

type TestTimestampTable struct {
	ID         int64
	Name       string
	Comment    *string
	CreateTime time.Time
	UpdateTime time.Time
}
